"""Constants for the Google Keep List Sync integration."""

DOMAIN = "gkeep_list_sync"
CONF_LIST_TITLE = "list_title"
CONF_LIST_ID = "list_id"
DEFAULT_LIST_TITLE = "Groceries"
MISSING_LIST = "missing_list"
SHOPPING_LIST_DOMAIN = "shopping_list"
SERVICE_NAME_BASE = "sync_list"
MASTER_TOKEN = "master_token"
